//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sale_Cars
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Orderdetails = new HashSet<Orderdetail>();
        }
    
        public int ProID { get; set; }
        public string ProName { get; set; }
        public string TinyDes { get; set; }
        public string FullDes { get; set; }
        public int Price { get; set; }
        public int CatID { get; set; }
        public int Quantity { get; set; }
        public int TypeID { get; set; }
        public int Sales { get; set; }
        public System.DateTime DOR { get; set; }
        public int Views { get; set; }
    
        public virtual ICollection<Orderdetail> Orderdetails { get; set; }
        public virtual Category Category { get; set; }
        public virtual Type Type { get; set; }
    }
}
